/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
    'third-party': ThirdPartyAuthOperations;
  };
  collections: {
    pages: Page;
    showcase: Showcase;
    blog: Blog;
    authors: Author;
    users: User;
    'third-party': ThirdParty;
    media: Media;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    showcase: ShowcaseSelect<false> | ShowcaseSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'third-party': ThirdPartySelect<false> | ThirdPartySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (ThirdParty & {
        collection: 'third-party';
      });
  jobs: {
    tasks: {
      screenshotWebpageTask: TaskScreenshotWebpageTask;
      updateMediaCollectionTask: TaskUpdateMediaCollectionTask;
      createMediaCollectionTask: TaskCreateMediaCollectionTask;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      createAndUpdateMediaWorkflow: WorkflowCreateAndUpdateMediaWorkflow;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ThirdPartyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * A page on the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  description: string;
  slug: string;
  blocks?: (HeroType | AboutSectionType | TitleWithBlocksType | CarouselType)[] | null;
  meta?: SeoType;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroType".
 */
export interface HeroType {
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Hero';
}
/**
 * Media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  blurData?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSectionType".
 */
export interface AboutSectionType {
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  showButton?: boolean | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'AboutSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithBlocksType".
 */
export interface TitleWithBlocksType {
  title: string;
  blocks: BlogPostsType[];
  showButton?: boolean | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TitleWithBlocks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPostsType".
 */
export interface BlogPostsType {
  onlyFeatured: boolean;
  limit: number;
  paginate?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'BlogPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselType".
 */
export interface CarouselType {
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoType".
 */
export interface SeoType {
  title?: string | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (number | null) | Media;
}
/**
 * A showcase page, awesome websites to check out.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcase".
 */
export interface Showcase {
  id: number;
  slug: string;
  title: string;
  url: string;
  /**
   * Screenshot is automatically generated based on URL, more fields will become available when job is done.
   */
  image?: (number | null) | Media;
  content?: {
    blocks?: RichTextType[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextType".
 */
export interface RichTextType {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'RichText';
}
/**
 * Blog posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  /**
   * This will be featured on the homepage
   */
  featured?: boolean | null;
  slug: string;
  authors: (number | Author)[];
  date: string;
  title: string;
  description: string;
  coverImage: number | Media;
  blocks?: (RichTextType | CodeType)[] | null;
  meta?: SeoType;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Authors of articles, blog posts, etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  isCompany?: boolean | null;
  slug: string;
  image?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  name: string;
  shortBio: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeType".
 */
export interface CodeType {
  spacing: 'py-4' | 'py-8' | 'py-16' | 'py-24' | 'py-32' | 'py-48' | 'py-64' | '';
  codeLanguage:
    | 'abap'
    | 'actionscript-3'
    | 'ada'
    | 'angular-html'
    | 'angular-ts'
    | 'apache'
    | 'apex'
    | 'apl'
    | 'applescript'
    | 'ara'
    | 'asciidoc'
    | 'asm'
    | 'astro'
    | 'awk'
    | 'ballerina'
    | 'bat'
    | 'beancount'
    | 'berry'
    | 'bibtex'
    | 'bicep'
    | 'blade'
    | 'bsl'
    | 'c'
    | 'cadence'
    | 'cairo'
    | 'clarity'
    | 'clojure'
    | 'cmake'
    | 'cobol'
    | 'codeowners'
    | 'codeql'
    | 'coffee'
    | 'common-lisp'
    | 'coq'
    | 'cpp'
    | 'crystal'
    | 'csharp'
    | 'css'
    | 'csv'
    | 'cue'
    | 'cypher'
    | 'd'
    | 'dart'
    | 'dax'
    | 'desktop'
    | 'diff'
    | 'docker'
    | 'dotenv'
    | 'dream-maker'
    | 'edge'
    | 'elixir'
    | 'elm'
    | 'emacs-lisp'
    | 'erb'
    | 'erlang'
    | 'fennel'
    | 'fish'
    | 'fluent'
    | 'fortran-fixed-form'
    | 'fortran-free-form'
    | 'fsharp'
    | 'gdresource'
    | 'gdscript'
    | 'gdshader'
    | 'genie'
    | 'gherkin'
    | 'git-commit'
    | 'git-rebase'
    | 'gleam'
    | 'glimmer-js'
    | 'glimmer-ts'
    | 'glsl'
    | 'gnuplot'
    | 'go'
    | 'graphql'
    | 'groovy'
    | 'hack'
    | 'haml'
    | 'handlebars'
    | 'haskell'
    | 'haxe'
    | 'hcl'
    | 'hjson'
    | 'hlsl'
    | 'html'
    | 'html-derivative'
    | 'http'
    | 'hxml'
    | 'hy'
    | 'imba'
    | 'ini'
    | 'java'
    | 'javascript'
    | 'jinja'
    | 'jison'
    | 'json'
    | 'json5'
    | 'jsonc'
    | 'jsonl'
    | 'jsonnet'
    | 'jssm'
    | 'jsx'
    | 'julia'
    | 'kotlin'
    | 'kusto'
    | 'latex'
    | 'lean'
    | 'less'
    | 'liquid'
    | 'log'
    | 'logo'
    | 'lua'
    | 'luau'
    | 'make'
    | 'markdown'
    | 'marko'
    | 'matlab'
    | 'mdc'
    | 'mdx'
    | 'mermaid'
    | 'mipsasm'
    | 'mojo'
    | 'move'
    | 'narrat'
    | 'nextflow'
    | 'nginx'
    | 'nim'
    | 'nix'
    | 'nushell'
    | 'objective-c'
    | 'objective-cpp'
    | 'ocaml'
    | 'pascal'
    | 'perl'
    | 'php'
    | 'plsql'
    | 'po'
    | 'polar'
    | 'postcss'
    | 'powerquery'
    | 'powershell'
    | 'prisma'
    | 'prolog'
    | 'proto'
    | 'pug'
    | 'puppet'
    | 'purescript'
    | 'python'
    | 'qml'
    | 'qmldir'
    | 'qss'
    | 'r'
    | 'racket'
    | 'raku'
    | 'razor'
    | 'reg'
    | 'regexp'
    | 'rel'
    | 'riscv'
    | 'rst'
    | 'ruby'
    | 'rust'
    | 'sas'
    | 'sass'
    | 'scala'
    | 'scheme'
    | 'scss'
    | 'sdbl'
    | 'shaderlab'
    | 'shellscript'
    | 'shellsession'
    | 'smalltalk'
    | 'solidity'
    | 'soy'
    | 'sparql'
    | 'splunk'
    | 'sql'
    | 'ssh-config'
    | 'stata'
    | 'stylus'
    | 'svelte'
    | 'swift'
    | 'system-verilog'
    | 'systemd'
    | 'talonscript'
    | 'tasl'
    | 'tcl'
    | 'templ'
    | 'terraform'
    | 'tex'
    | 'toml'
    | 'ts-tags'
    | 'tsv'
    | 'tsx'
    | 'turtle'
    | 'twig'
    | 'typescript'
    | 'typespec'
    | 'typst'
    | 'v'
    | 'vala'
    | 'vb'
    | 'verilog'
    | 'vhdl'
    | 'viml'
    | 'vue'
    | 'vue-html'
    | 'vyper'
    | 'wasm'
    | 'wenyan'
    | 'wgsl'
    | 'wikitext'
    | 'wolfram'
    | 'xml'
    | 'xsl'
    | 'yaml'
    | 'zenscript'
    | 'zig';
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Code';
}
/**
 * User accounts on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "third-party".
 */
export interface ThirdParty {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'screenshotWebpageTask' | 'updateMediaCollectionTask' | 'createMediaCollectionTask';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'createAndUpdateMediaWorkflow' | null;
  taskSlug?: ('inline' | 'screenshotWebpageTask' | 'updateMediaCollectionTask' | 'createMediaCollectionTask') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'showcase';
        value: number | Showcase;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'third-party';
        value: number | ThirdParty;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'third-party';
        value: number | ThirdParty;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'third-party';
        value: number | ThirdParty;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  blocks?:
    | T
    | {
        Hero?: T | HeroTypeSelect<T>;
        AboutSection?: T | AboutSectionTypeSelect<T>;
        TitleWithBlocks?: T | TitleWithBlocksTypeSelect<T>;
        Carousel?: T | CarouselTypeSelect<T>;
      };
  meta?: T | SeoTypeSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroType_select".
 */
export interface HeroTypeSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSectionType_select".
 */
export interface AboutSectionTypeSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  showButton?: T;
  buttonText?: T;
  buttonLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithBlocksType_select".
 */
export interface TitleWithBlocksTypeSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        BlogPosts?: T | BlogPostsTypeSelect<T>;
      };
  showButton?: T;
  buttonText?: T;
  buttonLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPostsType_select".
 */
export interface BlogPostsTypeSelect<T extends boolean = true> {
  onlyFeatured?: T;
  limit?: T;
  paginate?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselType_select".
 */
export interface CarouselTypeSelect<T extends boolean = true> {
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoType_select".
 */
export interface SeoTypeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcase_select".
 */
export interface ShowcaseSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  url?: T;
  image?: T;
  content?:
    | T
    | {
        blocks?:
          | T
          | {
              RichText?: T | RichTextTypeSelect<T>;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextType_select".
 */
export interface RichTextTypeSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  featured?: T;
  slug?: T;
  authors?: T;
  date?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  blocks?:
    | T
    | {
        RichText?: T | RichTextTypeSelect<T>;
        Code?: T | CodeTypeSelect<T>;
      };
  meta?: T | SeoTypeSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeType_select".
 */
export interface CodeTypeSelect<T extends boolean = true> {
  spacing?: T;
  codeLanguage?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  isCompany?: T;
  slug?: T;
  image?: T;
  coverImage?: T;
  name?: T;
  shortBio?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "third-party_select".
 */
export interface ThirdPartySelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurData?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site Settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  social?: {
    socialMedia?:
      | {
          icon:
            | 'Acorn'
            | 'AddressBook'
            | 'AddressBookTabs'
            | 'AirTrafficControl'
            | 'Airplane'
            | 'AirplaneInFlight'
            | 'AirplaneLanding'
            | 'AirplaneTakeoff'
            | 'AirplaneTaxiing'
            | 'AirplaneTilt'
            | 'Airplay'
            | 'Alarm'
            | 'Alien'
            | 'AlignBottom'
            | 'AlignBottomSimple'
            | 'AlignCenterHorizontal'
            | 'AlignCenterHorizontalSimple'
            | 'AlignCenterVertical'
            | 'AlignCenterVerticalSimple'
            | 'AlignLeft'
            | 'AlignLeftSimple'
            | 'AlignRight'
            | 'AlignRightSimple'
            | 'AlignTop'
            | 'AlignTopSimple'
            | 'AmazonLogo'
            | 'Ambulance'
            | 'Anchor'
            | 'AnchorSimple'
            | 'AndroidLogo'
            | 'Angle'
            | 'AngularLogo'
            | 'Aperture'
            | 'AppStoreLogo'
            | 'AppWindow'
            | 'AppleLogo'
            | 'ApplePodcastsLogo'
            | 'ApproximateEquals'
            | 'Archive'
            | 'Armchair'
            | 'ArrowArcLeft'
            | 'ArrowArcRight'
            | 'ArrowBendDoubleUpLeft'
            | 'ArrowBendDoubleUpRight'
            | 'ArrowBendDownLeft'
            | 'ArrowBendDownRight'
            | 'ArrowBendLeftDown'
            | 'ArrowBendLeftUp'
            | 'ArrowBendRightDown'
            | 'ArrowBendRightUp'
            | 'ArrowBendUpLeft'
            | 'ArrowBendUpRight'
            | 'ArrowCircleDown'
            | 'ArrowCircleDownLeft'
            | 'ArrowCircleDownRight'
            | 'ArrowCircleLeft'
            | 'ArrowCircleRight'
            | 'ArrowCircleUp'
            | 'ArrowCircleUpLeft'
            | 'ArrowCircleUpRight'
            | 'ArrowClockwise'
            | 'ArrowCounterClockwise'
            | 'ArrowDown'
            | 'ArrowDownLeft'
            | 'ArrowDownRight'
            | 'ArrowElbowDownLeft'
            | 'ArrowElbowDownRight'
            | 'ArrowElbowLeft'
            | 'ArrowElbowLeftDown'
            | 'ArrowElbowLeftUp'
            | 'ArrowElbowRight'
            | 'ArrowElbowRightDown'
            | 'ArrowElbowRightUp'
            | 'ArrowElbowUpLeft'
            | 'ArrowElbowUpRight'
            | 'ArrowFatDown'
            | 'ArrowFatLeft'
            | 'ArrowFatLineDown'
            | 'ArrowFatLineLeft'
            | 'ArrowFatLineRight'
            | 'ArrowFatLineUp'
            | 'ArrowFatLinesDown'
            | 'ArrowFatLinesLeft'
            | 'ArrowFatLinesRight'
            | 'ArrowFatLinesUp'
            | 'ArrowFatRight'
            | 'ArrowFatUp'
            | 'ArrowLeft'
            | 'ArrowLineDown'
            | 'ArrowLineDownLeft'
            | 'ArrowLineDownRight'
            | 'ArrowLineLeft'
            | 'ArrowLineRight'
            | 'ArrowLineUp'
            | 'ArrowLineUpLeft'
            | 'ArrowLineUpRight'
            | 'ArrowRight'
            | 'ArrowSquareDown'
            | 'ArrowSquareDownLeft'
            | 'ArrowSquareDownRight'
            | 'ArrowSquareIn'
            | 'ArrowSquareLeft'
            | 'ArrowSquareOut'
            | 'ArrowSquareRight'
            | 'ArrowSquareUp'
            | 'ArrowSquareUpLeft'
            | 'ArrowSquareUpRight'
            | 'ArrowUDownLeft'
            | 'ArrowUDownRight'
            | 'ArrowULeftDown'
            | 'ArrowULeftUp'
            | 'ArrowURightDown'
            | 'ArrowURightUp'
            | 'ArrowUUpLeft'
            | 'ArrowUUpRight'
            | 'ArrowUp'
            | 'ArrowUpLeft'
            | 'ArrowUpRight'
            | 'ArrowsClockwise'
            | 'ArrowsCounterClockwise'
            | 'ArrowsDownUp'
            | 'ArrowsHorizontal'
            | 'ArrowsIn'
            | 'ArrowsInCardinal'
            | 'ArrowsInLineHorizontal'
            | 'ArrowsInLineVertical'
            | 'ArrowsInSimple'
            | 'ArrowsLeftRight'
            | 'ArrowsMerge'
            | 'ArrowsOut'
            | 'ArrowsOutCardinal'
            | 'ArrowsOutLineHorizontal'
            | 'ArrowsOutLineVertical'
            | 'ArrowsOutSimple'
            | 'ArrowsSplit'
            | 'ArrowsVertical'
            | 'Article'
            | 'ArticleMedium'
            | 'ArticleNyTimes'
            | 'Asclepius'
            | 'Asterisk'
            | 'AsteriskSimple'
            | 'At'
            | 'Atom'
            | 'Avocado'
            | 'Axe'
            | 'Baby'
            | 'BabyCarriage'
            | 'Backpack'
            | 'Backspace'
            | 'Bag'
            | 'BagSimple'
            | 'Balloon'
            | 'Bandaids'
            | 'Bank'
            | 'Barbell'
            | 'Barcode'
            | 'Barn'
            | 'Barricade'
            | 'Baseball'
            | 'BaseballCap'
            | 'BaseballHelmet'
            | 'Basket'
            | 'Basketball'
            | 'Bathtub'
            | 'BatteryCharging'
            | 'BatteryChargingVertical'
            | 'BatteryEmpty'
            | 'BatteryFull'
            | 'BatteryHigh'
            | 'BatteryLow'
            | 'BatteryMedium'
            | 'BatteryPlus'
            | 'BatteryPlusVertical'
            | 'BatteryVerticalEmpty'
            | 'BatteryVerticalFull'
            | 'BatteryVerticalHigh'
            | 'BatteryVerticalLow'
            | 'BatteryVerticalMedium'
            | 'BatteryWarning'
            | 'BatteryWarningVertical'
            | 'BeachBall'
            | 'Beanie'
            | 'Bed'
            | 'BeerBottle'
            | 'BeerStein'
            | 'BehanceLogo'
            | 'Bell'
            | 'BellRinging'
            | 'BellSimple'
            | 'BellSimpleRinging'
            | 'BellSimpleSlash'
            | 'BellSimpleZ'
            | 'BellSlash'
            | 'BellZ'
            | 'Belt'
            | 'BezierCurve'
            | 'Bicycle'
            | 'Binary'
            | 'Binoculars'
            | 'Biohazard'
            | 'Bird'
            | 'Blueprint'
            | 'Bluetooth'
            | 'BluetoothConnected'
            | 'BluetoothSlash'
            | 'BluetoothX'
            | 'Boat'
            | 'Bomb'
            | 'Bone'
            | 'Book'
            | 'BookBookmark'
            | 'BookOpen'
            | 'BookOpenText'
            | 'BookOpenUser'
            | 'Bookmark'
            | 'BookmarkSimple'
            | 'Bookmarks'
            | 'BookmarksSimple'
            | 'Books'
            | 'Boot'
            | 'Boules'
            | 'BoundingBox'
            | 'BowlFood'
            | 'BowlSteam'
            | 'BowlingBall'
            | 'BoxArrowDown'
            | 'BoxArrowUp'
            | 'BoxingGlove'
            | 'BracketsAngle'
            | 'BracketsCurly'
            | 'BracketsRound'
            | 'BracketsSquare'
            | 'Brain'
            | 'Brandy'
            | 'Bread'
            | 'Bridge'
            | 'Briefcase'
            | 'BriefcaseMetal'
            | 'Broadcast'
            | 'Broom'
            | 'Browser'
            | 'Browsers'
            | 'Bug'
            | 'BugBeetle'
            | 'BugDroid'
            | 'Building'
            | 'BuildingApartment'
            | 'BuildingOffice'
            | 'Buildings'
            | 'Bulldozer'
            | 'Bus'
            | 'Butterfly'
            | 'CableCar'
            | 'Cactus'
            | 'Cake'
            | 'Calculator'
            | 'Calendar'
            | 'CalendarBlank'
            | 'CalendarCheck'
            | 'CalendarDot'
            | 'CalendarDots'
            | 'CalendarHeart'
            | 'CalendarMinus'
            | 'CalendarPlus'
            | 'CalendarSlash'
            | 'CalendarStar'
            | 'CalendarX'
            | 'CallBell'
            | 'Camera'
            | 'CameraPlus'
            | 'CameraRotate'
            | 'CameraSlash'
            | 'Campfire'
            | 'Car'
            | 'CarBattery'
            | 'CarProfile'
            | 'CarSimple'
            | 'Cardholder'
            | 'Cards'
            | 'CardsThree'
            | 'CaretCircleDoubleDown'
            | 'CaretCircleDoubleLeft'
            | 'CaretCircleDoubleRight'
            | 'CaretCircleDoubleUp'
            | 'CaretCircleDown'
            | 'CaretCircleLeft'
            | 'CaretCircleRight'
            | 'CaretCircleUp'
            | 'CaretCircleUpDown'
            | 'CaretDoubleDown'
            | 'CaretDoubleLeft'
            | 'CaretDoubleRight'
            | 'CaretDoubleUp'
            | 'CaretDown'
            | 'CaretLeft'
            | 'CaretLineDown'
            | 'CaretLineLeft'
            | 'CaretLineRight'
            | 'CaretLineUp'
            | 'CaretRight'
            | 'CaretUp'
            | 'CaretUpDown'
            | 'Carrot'
            | 'CashRegister'
            | 'CassetteTape'
            | 'CastleTurret'
            | 'Cat'
            | 'CellSignalFull'
            | 'CellSignalHigh'
            | 'CellSignalLow'
            | 'CellSignalMedium'
            | 'CellSignalNone'
            | 'CellSignalSlash'
            | 'CellSignalX'
            | 'CellTower'
            | 'Certificate'
            | 'Chair'
            | 'Chalkboard'
            | 'ChalkboardSimple'
            | 'ChalkboardTeacher'
            | 'Champagne'
            | 'ChargingStation'
            | 'ChartBar'
            | 'ChartBarHorizontal'
            | 'ChartDonut'
            | 'ChartLine'
            | 'ChartLineDown'
            | 'ChartLineUp'
            | 'ChartPie'
            | 'ChartPieSlice'
            | 'ChartPolar'
            | 'ChartScatter'
            | 'Chat'
            | 'ChatCentered'
            | 'ChatCenteredDots'
            | 'ChatCenteredSlash'
            | 'ChatCenteredText'
            | 'ChatCircle'
            | 'ChatCircleDots'
            | 'ChatCircleSlash'
            | 'ChatCircleText'
            | 'ChatDots'
            | 'ChatSlash'
            | 'ChatTeardrop'
            | 'ChatTeardropDots'
            | 'ChatTeardropSlash'
            | 'ChatTeardropText'
            | 'ChatText'
            | 'Chats'
            | 'ChatsCircle'
            | 'ChatsTeardrop'
            | 'Check'
            | 'CheckCircle'
            | 'CheckFat'
            | 'CheckSquare'
            | 'CheckSquareOffset'
            | 'Checkerboard'
            | 'Checks'
            | 'Cheers'
            | 'Cheese'
            | 'ChefHat'
            | 'Cherries'
            | 'Church'
            | 'Cigarette'
            | 'CigaretteSlash'
            | 'Circle'
            | 'CircleDashed'
            | 'CircleHalf'
            | 'CircleHalfTilt'
            | 'CircleNotch'
            | 'CirclesFour'
            | 'CirclesThree'
            | 'CirclesThreePlus'
            | 'Circuitry'
            | 'City'
            | 'Clipboard'
            | 'ClipboardText'
            | 'Clock'
            | 'ClockAfternoon'
            | 'ClockClockwise'
            | 'ClockCountdown'
            | 'ClockCounterClockwise'
            | 'ClockUser'
            | 'ClosedCaptioning'
            | 'Cloud'
            | 'CloudArrowDown'
            | 'CloudArrowUp'
            | 'CloudCheck'
            | 'CloudFog'
            | 'CloudLightning'
            | 'CloudMoon'
            | 'CloudRain'
            | 'CloudSlash'
            | 'CloudSnow'
            | 'CloudSun'
            | 'CloudWarning'
            | 'CloudX'
            | 'Clover'
            | 'Club'
            | 'CoatHanger'
            | 'CodaLogo'
            | 'Code'
            | 'CodeBlock'
            | 'CodeSimple'
            | 'CodepenLogo'
            | 'CodesandboxLogo'
            | 'Coffee'
            | 'CoffeeBean'
            | 'Coin'
            | 'CoinVertical'
            | 'Coins'
            | 'Columns'
            | 'ColumnsPlusLeft'
            | 'ColumnsPlusRight'
            | 'Command'
            | 'Compass'
            | 'CompassRose'
            | 'CompassTool'
            | 'ComputerTower'
            | 'Confetti'
            | 'ContactlessPayment'
            | 'Control'
            | 'Cookie'
            | 'CookingPot'
            | 'Copy'
            | 'CopySimple'
            | 'Copyleft'
            | 'Copyright'
            | 'CornersIn'
            | 'CornersOut'
            | 'Couch'
            | 'CourtBasketball'
            | 'Cow'
            | 'CowboyHat'
            | 'Cpu'
            | 'Crane'
            | 'CraneTower'
            | 'CreditCard'
            | 'Cricket'
            | 'Crop'
            | 'Cross'
            | 'Crosshair'
            | 'CrosshairSimple'
            | 'Crown'
            | 'CrownCross'
            | 'CrownSimple'
            | 'Cube'
            | 'CubeFocus'
            | 'CubeTransparent'
            | 'CurrencyBtc'
            | 'CurrencyCircleDollar'
            | 'CurrencyCny'
            | 'CurrencyDollar'
            | 'CurrencyDollarSimple'
            | 'CurrencyEth'
            | 'CurrencyEur'
            | 'CurrencyGbp'
            | 'CurrencyInr'
            | 'CurrencyJpy'
            | 'CurrencyKrw'
            | 'CurrencyKzt'
            | 'CurrencyNgn'
            | 'CurrencyRub'
            | 'Cursor'
            | 'CursorClick'
            | 'CursorText'
            | 'Cylinder'
            | 'Database'
            | 'Desk'
            | 'Desktop'
            | 'DesktopTower'
            | 'Detective'
            | 'DevToLogo'
            | 'DeviceMobile'
            | 'DeviceMobileCamera'
            | 'DeviceMobileSlash'
            | 'DeviceMobileSpeaker'
            | 'DeviceRotate'
            | 'DeviceTablet'
            | 'DeviceTabletCamera'
            | 'DeviceTabletSpeaker'
            | 'Devices'
            | 'Diamond'
            | 'DiamondsFour'
            | 'DiceFive'
            | 'DiceFour'
            | 'DiceOne'
            | 'DiceSix'
            | 'DiceThree'
            | 'DiceTwo'
            | 'Disc'
            | 'DiscoBall'
            | 'DiscordLogo'
            | 'Divide'
            | 'Dna'
            | 'Dog'
            | 'Door'
            | 'DoorOpen'
            | 'Dot'
            | 'DotOutline'
            | 'DotsNine'
            | 'DotsSix'
            | 'DotsSixVertical'
            | 'DotsThree'
            | 'DotsThreeCircle'
            | 'DotsThreeCircleVertical'
            | 'DotsThreeOutline'
            | 'DotsThreeOutlineVertical'
            | 'DotsThreeVertical'
            | 'Download'
            | 'DownloadSimple'
            | 'Dress'
            | 'Dresser'
            | 'DribbbleLogo'
            | 'Drone'
            | 'Drop'
            | 'DropHalf'
            | 'DropHalfBottom'
            | 'DropSimple'
            | 'DropSlash'
            | 'DropboxLogo'
            | 'Ear'
            | 'EarSlash'
            | 'Egg'
            | 'EggCrack'
            | 'Eject'
            | 'EjectSimple'
            | 'Elevator'
            | 'Empty'
            | 'Engine'
            | 'Envelope'
            | 'EnvelopeOpen'
            | 'EnvelopeSimple'
            | 'EnvelopeSimpleOpen'
            | 'Equalizer'
            | 'Equals'
            | 'Eraser'
            | 'EscalatorDown'
            | 'EscalatorUp'
            | 'Exam'
            | 'ExclamationMark'
            | 'Exclude'
            | 'ExcludeSquare'
            | 'Export'
            | 'Eye'
            | 'EyeClosed'
            | 'EyeSlash'
            | 'Eyedropper'
            | 'EyedropperSample'
            | 'Eyeglasses'
            | 'Eyes'
            | 'FaceMask'
            | 'FacebookLogo'
            | 'Factory'
            | 'Faders'
            | 'FadersHorizontal'
            | 'FalloutShelter'
            | 'Fan'
            | 'Farm'
            | 'FastForward'
            | 'FastForwardCircle'
            | 'Feather'
            | 'FediverseLogo'
            | 'FigmaLogo'
            | 'File'
            | 'FileArchive'
            | 'FileArrowDown'
            | 'FileArrowUp'
            | 'FileAudio'
            | 'FileC'
            | 'FileCSharp'
            | 'FileCloud'
            | 'FileCode'
            | 'FileCpp'
            | 'FileCss'
            | 'FileCsv'
            | 'FileDashed'
            | 'FileDoc'
            | 'FileHtml'
            | 'FileImage'
            | 'FileIni'
            | 'FileJpg'
            | 'FileJs'
            | 'FileJsx'
            | 'FileLock'
            | 'FileMagnifyingGlass'
            | 'FileMd'
            | 'FileMinus'
            | 'FilePdf'
            | 'FilePlus'
            | 'FilePng'
            | 'FilePpt'
            | 'FilePy'
            | 'FileRs'
            | 'FileSql'
            | 'FileSvg'
            | 'FileText'
            | 'FileTs'
            | 'FileTsx'
            | 'FileTxt'
            | 'FileVideo'
            | 'FileVue'
            | 'FileX'
            | 'FileXls'
            | 'FileZip'
            | 'Files'
            | 'FilmReel'
            | 'FilmScript'
            | 'FilmSlate'
            | 'FilmStrip'
            | 'Fingerprint'
            | 'FingerprintSimple'
            | 'FinnTheHuman'
            | 'Fire'
            | 'FireExtinguisher'
            | 'FireSimple'
            | 'FireTruck'
            | 'FirstAid'
            | 'FirstAidKit'
            | 'Fish'
            | 'FishSimple'
            | 'Flag'
            | 'FlagBanner'
            | 'FlagBannerFold'
            | 'FlagCheckered'
            | 'FlagPennant'
            | 'Flame'
            | 'Flashlight'
            | 'Flask'
            | 'FlipHorizontal'
            | 'FlipVertical'
            | 'FloppyDisk'
            | 'FloppyDiskBack'
            | 'FlowArrow'
            | 'Flower'
            | 'FlowerLotus'
            | 'FlowerTulip'
            | 'FlyingSaucer'
            | 'Folder'
            | 'FolderDashed'
            | 'FolderLock'
            | 'FolderMinus'
            | 'FolderOpen'
            | 'FolderPlus'
            | 'FolderSimple'
            | 'FolderSimpleDashed'
            | 'FolderSimpleLock'
            | 'FolderSimpleMinus'
            | 'FolderSimplePlus'
            | 'FolderSimpleStar'
            | 'FolderSimpleUser'
            | 'FolderStar'
            | 'FolderUser'
            | 'Folders'
            | 'Football'
            | 'FootballHelmet'
            | 'Footprints'
            | 'ForkKnife'
            | 'FourK'
            | 'FrameCorners'
            | 'FramerLogo'
            | 'Function'
            | 'Funnel'
            | 'FunnelSimple'
            | 'FunnelSimpleX'
            | 'FunnelX'
            | 'GameController'
            | 'Garage'
            | 'GasCan'
            | 'GasPump'
            | 'Gauge'
            | 'Gavel'
            | 'Gear'
            | 'GearFine'
            | 'GearSix'
            | 'GenderFemale'
            | 'GenderIntersex'
            | 'GenderMale'
            | 'GenderNeuter'
            | 'GenderNonbinary'
            | 'GenderTransgender'
            | 'Ghost'
            | 'Gif'
            | 'Gift'
            | 'GitBranch'
            | 'GitCommit'
            | 'GitDiff'
            | 'GitFork'
            | 'GitMerge'
            | 'GitPullRequest'
            | 'GithubLogo'
            | 'GitlabLogo'
            | 'GitlabLogoSimple'
            | 'Globe'
            | 'GlobeHemisphereEast'
            | 'GlobeHemisphereWest'
            | 'GlobeSimple'
            | 'GlobeSimpleX'
            | 'GlobeStand'
            | 'GlobeX'
            | 'Goggles'
            | 'Golf'
            | 'GoodreadsLogo'
            | 'GoogleCardboardLogo'
            | 'GoogleChromeLogo'
            | 'GoogleDriveLogo'
            | 'GoogleLogo'
            | 'GooglePhotosLogo'
            | 'GooglePlayLogo'
            | 'GooglePodcastsLogo'
            | 'Gps'
            | 'GpsFix'
            | 'GpsSlash'
            | 'Gradient'
            | 'GraduationCap'
            | 'Grains'
            | 'GrainsSlash'
            | 'Graph'
            | 'GraphicsCard'
            | 'GreaterThan'
            | 'GreaterThanOrEqual'
            | 'GridFour'
            | 'GridNine'
            | 'Guitar'
            | 'HairDryer'
            | 'Hamburger'
            | 'Hammer'
            | 'Hand'
            | 'HandArrowDown'
            | 'HandArrowUp'
            | 'HandCoins'
            | 'HandDeposit'
            | 'HandEye'
            | 'HandFist'
            | 'HandGrabbing'
            | 'HandHeart'
            | 'HandPalm'
            | 'HandPeace'
            | 'HandPointing'
            | 'HandSoap'
            | 'HandSwipeLeft'
            | 'HandSwipeRight'
            | 'HandTap'
            | 'HandWaving'
            | 'HandWithdraw'
            | 'Handbag'
            | 'HandbagSimple'
            | 'HandsClapping'
            | 'HandsPraying'
            | 'Handshake'
            | 'HardDrive'
            | 'HardDrives'
            | 'HardHat'
            | 'Hash'
            | 'HashStraight'
            | 'HeadCircuit'
            | 'Headlights'
            | 'Headphones'
            | 'Headset'
            | 'Heart'
            | 'HeartBreak'
            | 'HeartHalf'
            | 'HeartStraight'
            | 'HeartStraightBreak'
            | 'Heartbeat'
            | 'Hexagon'
            | 'HighDefinition'
            | 'HighHeel'
            | 'Highlighter'
            | 'HighlighterCircle'
            | 'Hockey'
            | 'Hoodie'
            | 'Horse'
            | 'Hospital'
            | 'Hourglass'
            | 'HourglassHigh'
            | 'HourglassLow'
            | 'HourglassMedium'
            | 'HourglassSimple'
            | 'HourglassSimpleHigh'
            | 'HourglassSimpleLow'
            | 'HourglassSimpleMedium'
            | 'House'
            | 'HouseLine'
            | 'HouseSimple'
            | 'Hurricane'
            | 'IceCream'
            | 'IdentificationBadge'
            | 'IdentificationCard'
            | 'Image'
            | 'ImageBroken'
            | 'ImageSquare'
            | 'Images'
            | 'ImagesSquare'
            | 'Infinity'
            | 'Info'
            | 'InstagramLogo'
            | 'Intersect'
            | 'IntersectSquare'
            | 'IntersectThree'
            | 'Intersection'
            | 'Invoice'
            | 'Island'
            | 'Jar'
            | 'JarLabel'
            | 'Jeep'
            | 'Joystick'
            | 'Kanban'
            | 'Key'
            | 'KeyReturn'
            | 'Keyboard'
            | 'Keyhole'
            | 'Knife'
            | 'Ladder'
            | 'LadderSimple'
            | 'Lamp'
            | 'LampPendant'
            | 'Laptop'
            | 'Lasso'
            | 'LastfmLogo'
            | 'Layout'
            | 'Leaf'
            | 'Lectern'
            | 'Lego'
            | 'LegoSmiley'
            | 'LessThan'
            | 'LessThanOrEqual'
            | 'LetterCircleH'
            | 'LetterCircleP'
            | 'LetterCircleV'
            | 'Lifebuoy'
            | 'Lightbulb'
            | 'LightbulbFilament'
            | 'Lighthouse'
            | 'Lightning'
            | 'LightningA'
            | 'LightningSlash'
            | 'LineSegment'
            | 'LineSegments'
            | 'LineVertical'
            | 'Link'
            | 'LinkBreak'
            | 'LinkSimple'
            | 'LinkSimpleBreak'
            | 'LinkSimpleHorizontal'
            | 'LinkSimpleHorizontalBreak'
            | 'LinkedinLogo'
            | 'LinktreeLogo'
            | 'LinuxLogo'
            | 'List'
            | 'ListBullets'
            | 'ListChecks'
            | 'ListDashes'
            | 'ListHeart'
            | 'ListMagnifyingGlass'
            | 'ListNumbers'
            | 'ListPlus'
            | 'ListStar'
            | 'Lock'
            | 'LockKey'
            | 'LockKeyOpen'
            | 'LockLaminated'
            | 'LockLaminatedOpen'
            | 'LockOpen'
            | 'LockSimple'
            | 'LockSimpleOpen'
            | 'Lockers'
            | 'Log'
            | 'MagicWand'
            | 'Magnet'
            | 'MagnetStraight'
            | 'MagnifyingGlass'
            | 'MagnifyingGlassMinus'
            | 'MagnifyingGlassPlus'
            | 'Mailbox'
            | 'MapPin'
            | 'MapPinArea'
            | 'MapPinLine'
            | 'MapPinPlus'
            | 'MapPinSimple'
            | 'MapPinSimpleArea'
            | 'MapPinSimpleLine'
            | 'MapTrifold'
            | 'MarkdownLogo'
            | 'MarkerCircle'
            | 'Martini'
            | 'MaskHappy'
            | 'MaskSad'
            | 'MastodonLogo'
            | 'MathOperations'
            | 'MatrixLogo'
            | 'Medal'
            | 'MedalMilitary'
            | 'MediumLogo'
            | 'Megaphone'
            | 'MegaphoneSimple'
            | 'MemberOf'
            | 'Memory'
            | 'MessengerLogo'
            | 'MetaLogo'
            | 'Meteor'
            | 'Metronome'
            | 'Microphone'
            | 'MicrophoneSlash'
            | 'MicrophoneStage'
            | 'Microscope'
            | 'MicrosoftExcelLogo'
            | 'MicrosoftOutlookLogo'
            | 'MicrosoftPowerpointLogo'
            | 'MicrosoftTeamsLogo'
            | 'MicrosoftWordLogo'
            | 'Minus'
            | 'MinusCircle'
            | 'MinusSquare'
            | 'Money'
            | 'MoneyWavy'
            | 'Monitor'
            | 'MonitorArrowUp'
            | 'MonitorPlay'
            | 'Moon'
            | 'MoonStars'
            | 'Moped'
            | 'MopedFront'
            | 'Mosque'
            | 'Motorcycle'
            | 'Mountains'
            | 'Mouse'
            | 'MouseLeftClick'
            | 'MouseMiddleClick'
            | 'MouseRightClick'
            | 'MouseScroll'
            | 'MouseSimple'
            | 'MusicNote'
            | 'MusicNoteSimple'
            | 'MusicNotes'
            | 'MusicNotesMinus'
            | 'MusicNotesPlus'
            | 'MusicNotesSimple'
            | 'NavigationArrow'
            | 'Needle'
            | 'Network'
            | 'NetworkSlash'
            | 'NetworkX'
            | 'Newspaper'
            | 'NewspaperClipping'
            | 'NotEquals'
            | 'NotMemberOf'
            | 'NotSubsetOf'
            | 'NotSupersetOf'
            | 'Notches'
            | 'Note'
            | 'NoteBlank'
            | 'NotePencil'
            | 'Notebook'
            | 'Notepad'
            | 'Notification'
            | 'NotionLogo'
            | 'NuclearPlant'
            | 'NumberCircleEight'
            | 'NumberCircleFive'
            | 'NumberCircleFour'
            | 'NumberCircleNine'
            | 'NumberCircleOne'
            | 'NumberCircleSeven'
            | 'NumberCircleSix'
            | 'NumberCircleThree'
            | 'NumberCircleTwo'
            | 'NumberCircleZero'
            | 'NumberEight'
            | 'NumberFive'
            | 'NumberFour'
            | 'NumberNine'
            | 'NumberOne'
            | 'NumberSeven'
            | 'NumberSix'
            | 'NumberSquareEight'
            | 'NumberSquareFive'
            | 'NumberSquareFour'
            | 'NumberSquareNine'
            | 'NumberSquareOne'
            | 'NumberSquareSeven'
            | 'NumberSquareSix'
            | 'NumberSquareThree'
            | 'NumberSquareTwo'
            | 'NumberSquareZero'
            | 'NumberThree'
            | 'NumberTwo'
            | 'NumberZero'
            | 'Numpad'
            | 'Nut'
            | 'NyTimesLogo'
            | 'Octagon'
            | 'OfficeChair'
            | 'Onigiri'
            | 'OpenAiLogo'
            | 'Option'
            | 'Orange'
            | 'OrangeSlice'
            | 'Oven'
            | 'Package'
            | 'PaintBrush'
            | 'PaintBrushBroad'
            | 'PaintBrushHousehold'
            | 'PaintBucket'
            | 'PaintRoller'
            | 'Palette'
            | 'Panorama'
            | 'Pants'
            | 'PaperPlane'
            | 'PaperPlaneRight'
            | 'PaperPlaneTilt'
            | 'Paperclip'
            | 'PaperclipHorizontal'
            | 'Parachute'
            | 'Paragraph'
            | 'Parallelogram'
            | 'Park'
            | 'Password'
            | 'Path'
            | 'PatreonLogo'
            | 'Pause'
            | 'PauseCircle'
            | 'PawPrint'
            | 'PaypalLogo'
            | 'Peace'
            | 'Pen'
            | 'PenNib'
            | 'PenNibStraight'
            | 'Pencil'
            | 'PencilCircle'
            | 'PencilLine'
            | 'PencilRuler'
            | 'PencilSimple'
            | 'PencilSimpleLine'
            | 'PencilSimpleSlash'
            | 'PencilSlash'
            | 'Pentagon'
            | 'Pentagram'
            | 'Pepper'
            | 'Percent'
            | 'Person'
            | 'PersonArmsSpread'
            | 'PersonSimple'
            | 'PersonSimpleBike'
            | 'PersonSimpleCircle'
            | 'PersonSimpleHike'
            | 'PersonSimpleRun'
            | 'PersonSimpleSki'
            | 'PersonSimpleSnowboard'
            | 'PersonSimpleSwim'
            | 'PersonSimpleTaiChi'
            | 'PersonSimpleThrow'
            | 'PersonSimpleWalk'
            | 'Perspective'
            | 'Phone'
            | 'PhoneCall'
            | 'PhoneDisconnect'
            | 'PhoneIncoming'
            | 'PhoneList'
            | 'PhoneOutgoing'
            | 'PhonePause'
            | 'PhonePlus'
            | 'PhoneSlash'
            | 'PhoneTransfer'
            | 'PhoneX'
            | 'PhosphorLogo'
            | 'Pi'
            | 'PianoKeys'
            | 'PicnicTable'
            | 'PictureInPicture'
            | 'PiggyBank'
            | 'Pill'
            | 'PingPong'
            | 'PintGlass'
            | 'PinterestLogo'
            | 'Pinwheel'
            | 'Pipe'
            | 'PipeWrench'
            | 'PixLogo'
            | 'Pizza'
            | 'Placeholder'
            | 'Planet'
            | 'Plant'
            | 'Play'
            | 'PlayCircle'
            | 'PlayPause'
            | 'Playlist'
            | 'Plug'
            | 'PlugCharging'
            | 'Plugs'
            | 'PlugsConnected'
            | 'Plus'
            | 'PlusCircle'
            | 'PlusMinus'
            | 'PlusSquare'
            | 'PokerChip'
            | 'PoliceCar'
            | 'Polygon'
            | 'Popcorn'
            | 'Popsicle'
            | 'PottedPlant'
            | 'Power'
            | 'Prescription'
            | 'Presentation'
            | 'PresentationChart'
            | 'Printer'
            | 'Prohibit'
            | 'ProhibitInset'
            | 'ProjectorScreen'
            | 'ProjectorScreenChart'
            | 'Pulse'
            | 'PushPin'
            | 'PushPinSimple'
            | 'PushPinSimpleSlash'
            | 'PushPinSlash'
            | 'PuzzlePiece'
            | 'QrCode'
            | 'Question'
            | 'QuestionMark'
            | 'Queue'
            | 'Quotes'
            | 'Rabbit'
            | 'Racquet'
            | 'Radical'
            | 'Radio'
            | 'RadioButton'
            | 'Radioactive'
            | 'Rainbow'
            | 'RainbowCloud'
            | 'Ranking'
            | 'ReadCvLogo'
            | 'Receipt'
            | 'ReceiptX'
            | 'Record'
            | 'Rectangle'
            | 'RectangleDashed'
            | 'Recycle'
            | 'RedditLogo'
            | 'Repeat'
            | 'RepeatOnce'
            | 'ReplitLogo'
            | 'Resize'
            | 'Rewind'
            | 'RewindCircle'
            | 'RoadHorizon'
            | 'Robot'
            | 'Rocket'
            | 'RocketLaunch'
            | 'Rows'
            | 'RowsPlusBottom'
            | 'RowsPlusTop'
            | 'Rss'
            | 'RssSimple'
            | 'Rug'
            | 'Ruler'
            | 'Sailboat'
            | 'Scales'
            | 'Scan'
            | 'ScanSmiley'
            | 'Scissors'
            | 'Scooter'
            | 'Screencast'
            | 'Screwdriver'
            | 'Scribble'
            | 'ScribbleLoop'
            | 'Scroll'
            | 'Seal'
            | 'SealCheck'
            | 'SealPercent'
            | 'SealQuestion'
            | 'SealWarning'
            | 'Seat'
            | 'Seatbelt'
            | 'SecurityCamera'
            | 'Selection'
            | 'SelectionAll'
            | 'SelectionBackground'
            | 'SelectionForeground'
            | 'SelectionInverse'
            | 'SelectionPlus'
            | 'SelectionSlash'
            | 'Shapes'
            | 'Share'
            | 'ShareFat'
            | 'ShareNetwork'
            | 'Shield'
            | 'ShieldCheck'
            | 'ShieldCheckered'
            | 'ShieldChevron'
            | 'ShieldPlus'
            | 'ShieldSlash'
            | 'ShieldStar'
            | 'ShieldWarning'
            | 'ShippingContainer'
            | 'ShirtFolded'
            | 'ShootingStar'
            | 'ShoppingBag'
            | 'ShoppingBagOpen'
            | 'ShoppingCart'
            | 'ShoppingCartSimple'
            | 'Shovel'
            | 'Shower'
            | 'Shrimp'
            | 'Shuffle'
            | 'ShuffleAngular'
            | 'ShuffleSimple'
            | 'Sidebar'
            | 'SidebarSimple'
            | 'Sigma'
            | 'SignIn'
            | 'SignOut'
            | 'Signature'
            | 'Signpost'
            | 'SimCard'
            | 'Siren'
            | 'SketchLogo'
            | 'SkipBack'
            | 'SkipBackCircle'
            | 'SkipForward'
            | 'SkipForwardCircle'
            | 'Skull'
            | 'SkypeLogo'
            | 'SlackLogo'
            | 'Sliders'
            | 'SlidersHorizontal'
            | 'Slideshow'
            | 'Smiley'
            | 'SmileyAngry'
            | 'SmileyBlank'
            | 'SmileyMeh'
            | 'SmileyMelting'
            | 'SmileyNervous'
            | 'SmileySad'
            | 'SmileySticker'
            | 'SmileyWink'
            | 'SmileyXEyes'
            | 'SnapchatLogo'
            | 'Sneaker'
            | 'SneakerMove'
            | 'Snowflake'
            | 'SoccerBall'
            | 'Sock'
            | 'SolarPanel'
            | 'SolarRoof'
            | 'SortAscending'
            | 'SortDescending'
            | 'SoundcloudLogo'
            | 'Spade'
            | 'Sparkle'
            | 'SpeakerHifi'
            | 'SpeakerHigh'
            | 'SpeakerLow'
            | 'SpeakerNone'
            | 'SpeakerSimpleHigh'
            | 'SpeakerSimpleLow'
            | 'SpeakerSimpleNone'
            | 'SpeakerSimpleSlash'
            | 'SpeakerSimpleX'
            | 'SpeakerSlash'
            | 'SpeakerX'
            | 'Speedometer'
            | 'Sphere'
            | 'Spinner'
            | 'SpinnerBall'
            | 'SpinnerGap'
            | 'Spiral'
            | 'SplitHorizontal'
            | 'SplitVertical'
            | 'SpotifyLogo'
            | 'SprayBottle'
            | 'Square'
            | 'SquareHalf'
            | 'SquareHalfBottom'
            | 'SquareLogo'
            | 'SquareSplitHorizontal'
            | 'SquareSplitVertical'
            | 'SquaresFour'
            | 'Stack'
            | 'StackMinus'
            | 'StackOverflowLogo'
            | 'StackPlus'
            | 'StackSimple'
            | 'Stairs'
            | 'Stamp'
            | 'StandardDefinition'
            | 'Star'
            | 'StarAndCrescent'
            | 'StarFour'
            | 'StarHalf'
            | 'StarOfDavid'
            | 'SteamLogo'
            | 'SteeringWheel'
            | 'Steps'
            | 'Stethoscope'
            | 'Sticker'
            | 'Stool'
            | 'Stop'
            | 'StopCircle'
            | 'Storefront'
            | 'Strategy'
            | 'StripeLogo'
            | 'Student'
            | 'SubsetOf'
            | 'SubsetProperOf'
            | 'Subtitles'
            | 'SubtitlesSlash'
            | 'Subtract'
            | 'SubtractSquare'
            | 'Subway'
            | 'Suitcase'
            | 'SuitcaseRolling'
            | 'SuitcaseSimple'
            | 'Sun'
            | 'SunDim'
            | 'SunHorizon'
            | 'Sunglasses'
            | 'SupersetOf'
            | 'SupersetProperOf'
            | 'Swap'
            | 'Swatches'
            | 'SwimmingPool'
            | 'Sword'
            | 'Synagogue'
            | 'Syringe'
            | 'TShirt'
            | 'Table'
            | 'Tabs'
            | 'Tag'
            | 'TagChevron'
            | 'TagSimple'
            | 'Target'
            | 'Taxi'
            | 'TeaBag'
            | 'TelegramLogo'
            | 'Television'
            | 'TelevisionSimple'
            | 'TennisBall'
            | 'Tent'
            | 'Terminal'
            | 'TerminalWindow'
            | 'TestTube'
            | 'TextAUnderline'
            | 'TextAa'
            | 'TextAlignCenter'
            | 'TextAlignJustify'
            | 'TextAlignLeft'
            | 'TextAlignRight'
            | 'TextB'
            | 'TextColumns'
            | 'TextH'
            | 'TextHFive'
            | 'TextHFour'
            | 'TextHOne'
            | 'TextHSix'
            | 'TextHThree'
            | 'TextHTwo'
            | 'TextIndent'
            | 'TextItalic'
            | 'TextOutdent'
            | 'TextStrikethrough'
            | 'TextSubscript'
            | 'TextSuperscript'
            | 'TextT'
            | 'TextTSlash'
            | 'TextUnderline'
            | 'Textbox'
            | 'Thermometer'
            | 'ThermometerCold'
            | 'ThermometerHot'
            | 'ThermometerSimple'
            | 'ThreadsLogo'
            | 'ThreeD'
            | 'ThumbsDown'
            | 'ThumbsUp'
            | 'Ticket'
            | 'TidalLogo'
            | 'TiktokLogo'
            | 'Tilde'
            | 'Timer'
            | 'TipJar'
            | 'Tipi'
            | 'Tire'
            | 'ToggleLeft'
            | 'ToggleRight'
            | 'Toilet'
            | 'ToiletPaper'
            | 'Toolbox'
            | 'Tooth'
            | 'Tornado'
            | 'Tote'
            | 'ToteSimple'
            | 'Towel'
            | 'Tractor'
            | 'Trademark'
            | 'TrademarkRegistered'
            | 'TrafficCone'
            | 'TrafficSign'
            | 'TrafficSignal'
            | 'Train'
            | 'TrainRegional'
            | 'TrainSimple'
            | 'Tram'
            | 'Translate'
            | 'Trash'
            | 'TrashSimple'
            | 'Tray'
            | 'TrayArrowDown'
            | 'TrayArrowUp'
            | 'TreasureChest'
            | 'Tree'
            | 'TreeEvergreen'
            | 'TreePalm'
            | 'TreeStructure'
            | 'TreeView'
            | 'TrendDown'
            | 'TrendUp'
            | 'Triangle'
            | 'TriangleDashed'
            | 'Trolley'
            | 'TrolleySuitcase'
            | 'Trophy'
            | 'Truck'
            | 'TruckTrailer'
            | 'TumblrLogo'
            | 'TwitchLogo'
            | 'TwitterLogo'
            | 'Umbrella'
            | 'UmbrellaSimple'
            | 'Union'
            | 'Unite'
            | 'UniteSquare'
            | 'Upload'
            | 'UploadSimple'
            | 'Usb'
            | 'User'
            | 'UserCheck'
            | 'UserCircle'
            | 'UserCircleCheck'
            | 'UserCircleDashed'
            | 'UserCircleGear'
            | 'UserCircleMinus'
            | 'UserCirclePlus'
            | 'UserFocus'
            | 'UserGear'
            | 'UserList'
            | 'UserMinus'
            | 'UserPlus'
            | 'UserRectangle'
            | 'UserSound'
            | 'UserSquare'
            | 'UserSwitch'
            | 'Users'
            | 'UsersFour'
            | 'UsersThree'
            | 'Van'
            | 'Vault'
            | 'VectorThree'
            | 'VectorTwo'
            | 'Vibrate'
            | 'Video'
            | 'VideoCamera'
            | 'VideoCameraSlash'
            | 'VideoConference'
            | 'Vignette'
            | 'VinylRecord'
            | 'VirtualReality'
            | 'Virus'
            | 'Visor'
            | 'Voicemail'
            | 'Volleyball'
            | 'Wall'
            | 'Wallet'
            | 'Warehouse'
            | 'Warning'
            | 'WarningCircle'
            | 'WarningDiamond'
            | 'WarningOctagon'
            | 'WashingMachine'
            | 'Watch'
            | 'WaveSawtooth'
            | 'WaveSine'
            | 'WaveSquare'
            | 'WaveTriangle'
            | 'Waveform'
            | 'WaveformSlash'
            | 'Waves'
            | 'Webcam'
            | 'WebcamSlash'
            | 'WebhooksLogo'
            | 'WechatLogo'
            | 'WhatsappLogo'
            | 'Wheelchair'
            | 'WheelchairMotion'
            | 'WifiHigh'
            | 'WifiLow'
            | 'WifiMedium'
            | 'WifiNone'
            | 'WifiSlash'
            | 'WifiX'
            | 'Wind'
            | 'Windmill'
            | 'WindowsLogo'
            | 'Wine'
            | 'Wrench'
            | 'X'
            | 'XCircle'
            | 'XLogo'
            | 'XSquare'
            | 'Yarn'
            | 'YinYang'
            | 'YoutubeLogo';
          label: string;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  navigation: {
    links: {
      label: string;
      link: string;
      id?: string | null;
    }[];
  };
  footer: {
    text?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links: {
      label: string;
      link: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  social?:
    | T
    | {
        socialMedia?:
          | T
          | {
              icon?: T;
              label?: T;
              link?: T;
              id?: T;
            };
      };
  navigation?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        text?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScreenshotWebpageTask".
 */
export interface TaskScreenshotWebpageTask {
  input: {
    showcaseID: number;
    url: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdateMediaCollectionTask".
 */
export interface TaskUpdateMediaCollectionTask {
  input: {
    showcaseID: number;
    media: number | Media;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateMediaCollectionTask".
 */
export interface TaskCreateMediaCollectionTask {
  input: {
    filename: string;
    buffer:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output: {
    media: number | Media;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowCreateAndUpdateMediaWorkflow".
 */
export interface WorkflowCreateAndUpdateMediaWorkflow {
  input: {
    showcaseID: string;
    buffer:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    filename: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}